//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Checkout = new HashSet<Checkout>();
            this.Feedback = new HashSet<Feedback>();
        }

        public DB.Book Clone()
        {
            Book clone = new Book
            {
                IdBook = this.IdBook,
                Name = this.Name,
                Author = this.Author,
                IdPublishingHouse = this.IdPublishingHouse,
                PublishingYear = this.PublishingYear,
                NumberOfPages = this.NumberOfPages,
                IdGenre = this.IdGenre,
                IdStatus = this.IdStatus,
                Photo = this.Photo,
            };

            return clone;
        }

        public void CopyFrom(Book other)
        {
            if (other != null)
            {
                this.IdBook = other.IdBook;
                this.Name = other.Name;
                this.Author = other.Author;
                this.IdPublishingHouse = other.IdPublishingHouse;
                this.PublishingYear = other.PublishingYear;
                this.NumberOfPages = other.NumberOfPages;
                this.IdGenre = other.IdGenre;
                this.IdStatus = other.IdStatus;
                this.Photo = other.Photo;
            }
        }



        public int IdBook { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public int IdPublishingHouse { get; set; }
        public int PublishingYear { get; set; }
        public int NumberOfPages { get; set; }
        public int IdGenre { get; set; }
        public int IdStatus { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual PublishingHouse PublishingHouse { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checkout> Checkout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedback { get; set; }
    }
}
