//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkout
    {
        public int IdCheckout { get; set; }
        public int IdBook { get; set; }
        public int IdReader { get; set; }
        public int IdLibrarianCheckout { get; set; }
        public Nullable<int> IdLibrarianReturn { get; set; }
        public System.DateTime DateCheckout { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Librarian Librarian { get; set; }
        public virtual Librarian Librarian1 { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
