//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Reader = new HashSet<Reader>();
        }

        public DB.Event Clone()
        {
            Event clone = new Event
            {
                IdEvent = this.IdEvent,
                Name = this.Name,
                EventDateTime = this.EventDateTime,
                Photo = this.Photo,
                IdLibrarian = this.IdLibrarian,
            };

            return clone;
        }

        public void CopyFrom(Event other)
        {
            if (other != null)
            {
                this.IdEvent = other.IdEvent;
                this.Name = other.Name;
                this.EventDateTime = other.EventDateTime;
                this.Photo = other.Photo;
                this.IdLibrarian = other.IdLibrarian;
            }
        }

        public int IdEvent { get; set; }
        public string Name { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public byte[] Photo { get; set; }
        public int IdLibrarian { get; set; }
    
        public virtual Librarian Librarian { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reader> Reader { get; set; }
    }
}
