//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int IdFeedback { get; set; }
        public int IdReader { get; set; }
        public int IdBook { get; set; }
        public System.DateTime FeedbackDate { get; set; }
        public string FeedbackText { get; set; }
        public byte Rating { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
