//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reader()
        {
            this.Checkout = new HashSet<Checkout>();
            this.Feedback = new HashSet<Feedback>();
            this.Event = new HashSet<Event>();
        }

        public DB.Reader Clone()
        {
            Reader clone = new Reader
            {
                IdReader = this.IdReader,
                LastName = this.LastName,
                FirstName = this.FirstName,
                Patronymic = this.Patronymic,
                Login = this.Login,
                Password = this.Password,
                Birthday = this.Birthday,
                Phone = this.Phone,
                RegistrationDate = this.RegistrationDate,
            };

            return clone;
        }

        public void CopyFrom(Reader other)
        {
            if (other != null)
            {

                this.IdReader = other.IdReader;
                this.LastName = other.LastName;
                this.FirstName = other.FirstName;
                this.Patronymic = other.Patronymic;
                this.Login = other.Login;
                this.Password = other.Password;
                this.Birthday = other.Birthday;
                this.Phone = other.Phone;
                this.RegistrationDate = other.RegistrationDate;
            }
        }

        public int IdReader { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Phone { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checkout> Checkout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Event { get; set; }
    }
}
